export const TAG_LOGIC_PROPERTY = 'exports'
export const TAG_CSS_PROPERTY = 'css'
export const TAG_TEMPLATE_PROPERTY = 'template'
export const TAG_NAME_PROPERTY = 'name'
export const RIOT_MODULE_ID = 'riot'
export const RIOT_INTERFACE_WRAPPER_NAME = 'RiotComponentWrapper'
export const RIOT_TAG_INTERFACE_NAME = 'RiotComponent'
