/**
 * Generate the component css
 * @param   { Object } sourceNode - node generated by the riot compiler
 * @param   { Object } options - user options
 * @param   { Output } output - current compiler output
 * @returns { Promise<Output> } - enhanced output with the result of the current generator
 */
export default async function css(sourceNode, options, { code, map }) { // eslint-disable-line
  return await {
    code,
    map
  }
}